docstring added to task
GSTT-CSC/hazen-web-app pull request #103
Opened 2023-01-26 21:05 UTC by Lucrezia-Cester

2023-02-20 10:11 UTC, tomaroberts commented
@Lucrezia-Cester 

Can you describe this PR a bit more for me please? And add a screenshot showing the change.

Also, you have committed your Python virtual environment with this PR – please can you remove it.

2023-02-21 08:18 UTC, Lucrezia-Cester commented
Hi @tomaroberts , this PR is linked to an issue (see development issue) and I just solved the issue that was described

2023-03-24 14:44 UTC, heyhaleema requested changes
@Lucrezia-Cester Could you please push another commit to remove the virtual environment e.g., outright delete the `hazen-web-app/` or update the `.gitignore` so this is excluded?

2023-03-24 14:46 UTC, heyhaleema commented
> @Lucrezia-Cester Could you please push another commit to remove the virtual environment e.g., outright delete `hazen-web-app/` or update the `.gitignore` so this is excluded?

This is so the folder and files in the red box below won't be included in the files changed:

![image](https://user-images.githubusercontent.com/67117138/227557933-d60288d9-be5e-4ebf-8314-7cde5db17558.png)

2023-04-04 14:54 UTC, Lucrezia-Cester commented
hi @hshuaib90, could you please take a look at this PR? I have added a column to the Task table to store docstring data.

When I try to use alembic to generate a migration I get this error

lce21@medphys026-mac hazen-web-app % alembic revision --autogenerate -m "Add docstring column to task table"

  FAILED: No config file 'alembic.ini' found, or file has no '[alembic]' section


and I can't figure out how to fix this.

2023-04-04 22:14 UTC, Lucrezia-Cester commented
@hshuaib90, @heyhaleema , this is now ready for review, docstring is added to database in task table if the docstring is present in the original hazenlib task.

https://user-images.githubusercontent.com/83493021/229934530-b586eac0-6c14-4a9e-82c2-4f8ff44ae0dd.mov

2023-04-18 14:32 UTC, heyhaleema commented on alembic_runner.py
@Lucrezia-Cester As discussed, I just wanted to double-check whether this should be pushed to the repo i.e., since it's referencing a local file. Also, for updating local copies of the DB, I think we should discuss this process a bit more and add these instructions to the README e.g., I'm assuming the revision message will need to be updated depending on what updates we make.

2023-04-18 14:33 UTC, heyhaleema commented on hazen.py
> +                db.session.commit()
@Lucrezia-Cester I think the issue I'm having is that this line doesn't seem to be committing the docstrings to my `Tasks` table.

2023-04-18 14:44 UTC, heyhaleema commented on hazen.py
> +    def get_module_docstring(filepath):
If we keep this function in e.g., not use a module's `__doc__` global, I suggest we move this outside the `register_tasks_in_db` function.

2024-01-17 10:34 UTC, sophie22 commented
Task description will be described in the ReadTheDocs autogenerated from the hazenlib docstrings and additional descriptions by MR physicists to other users. This PR and change is no longer required.

2024-01-17 10:34 UTC, closed without merging